

--    													**--CASE STUDY ON CAB BOOKING SYSTEM--** 				 			 								     			-- 

create database Cab_booking_system;
use Cab_booking_system;
--																-- Tables In Database--																    					-- 																													   
show tables;
SELECT * FROM booking; 
SELECT * FROM customers;
SELECT * FROM drivers;
SELECT * FROM trip_details;
SELECT * FROM vehicles;
select * from feedback;

SET SQL_SAFE_UPDATES = 0;
--																-- Record in Our tables --																					-- 	
SELECT count(*) FROM booking;
SELECT count(*) FROM customers;
SELECT count(*) FROM drivers;
SELECT count(*) FROM trip_details;
SELECT count(*) FROM vehicles;
select count(*) from feedback;


-- 																-- This Project's aims is:-- 																				-- 																		
-- Monitor ongoing and completed bookings. 
 -- - Track customer preferences and behavior. 
 -- - Evaluate driver efficiency and performance. 
 -- - Analyze revenue trends based on fares and trip details. 
 -- - Identify operational bottlenecks and areas for improvement.



-- 																-- Customer and Booking Analysis-- 																		    -- 																			--

-- (1.) Identify customers who have completed the most bookings. What insights can you draw about their behavior?  
-- Ans.
 Select c.name, count(c.customer_id) as Number_of_Bookings from customers c join booking b 
 on c.customer_id=b.customer_id
 where b.status = "Completed" 
 group by c.name
 Order by
 count(c.customer_id) DESC;
 
 
 -- (2.) Find customers who have canceled more than 30% of their total bookings. find Customer name who cancel mostly their Cab? 
 -- ANS. 
 select c.name,
count(*) as total_bookings,
SUM(b.status="cancelled") as cancelled_booking ,
round(sum(b.status="cancelled")/count(*)*100)as cancel_percent
from customers c
join booking b on b.customer_id=c.customer_id
group by c.name
having cancel_percent>30
order by cancel_percent DESC;

-- (3.) Determine the busiest day of the week for bookings. How can the company optimize cab availability on peak days? 
 -- Ans.
select  dayname(trip_start_time)  Day_of_week,
count(*)  total_bookings
from booking
group by  dayname(trip_start_time)
order by total_bookings desc
limit 1 ,5;


--															-- Driver Performance & Efficiency--    																		-- 
-- (4.) Identify drivers who have received an average rating below 3.0 . 
select name,
ROUND(AVG(rating),2) as average_rating 
from drivers
group by name
having average_rating>3.0
order by average_rating DESC;


-- (5.) Find the top 5 drivers who have completed the longest trips in terms of distance. 
-- Ans.
 Select driver_id ,count(*) as Total_rides,
round(max(trip_distance_km),2) as longest_trip
from trip_details 
where trip_status ="completed"
group by driver_id
order by longest_trip Desc
Limit 5;



-- (6.) Identify drivers with a high percentage of canceled trips. Could this indicate driver  unreliability? 
-- Ans. 
Select driver_id ,count(*) as total_rides,
sum(case when trip_status = "cancelled" then 1 else 0 end) as Cancelled_rides,
round(100*sum(case when trip_status ="cancelled" then 1 else 0 End )/count(*),2) as Percent_cancelled
from trip_details
where driver_id is not null
group by driver_id
order by Percent_cancelled DESC;

--															 -- Revenue & Business Metrics--																				--   																--  
-- (7.) Calculate the total revenue generated by completed bookings. what Revenue collected by company? 
-- Ans. 
select sum(t.fare_amount) as Total_Revenue
from trip_details t 
inner join booking b 
on t.customer_id=b.customer_id
where t.trip_status="Completed";


-- (8.) Identify the top 3 most frequently traveled routes based on PickupLocation and DropoffLocation. Should the company allocate more cabs to these routes? 
-- Ans.
select pickup_location, drop_location, COUNT(*) as trip_count
From booking
GROUP BY pickup_location, drop_location
Order by trip_count DESC
Limit 3;


-- (9.) Determine if higher-rated drivers tend to complete more trips and earn higher fares. Is there a direct correlation between driver ratings and earnings? 
-- Ans.
Select c.name, round(Avg(b.fare_amount),2) as Avg_Fare_Amount,
 SUM(b.fare_amount) as Total_Earning
From customers c 
join booking b
on c.customer_id=b.customer_id
where b.status ="Completed"
Group by c.name
order by avg_Fare_Amount DESC;



-- 															-- Operational Efficiency & Optimization-- 																        -- 
-- (10.) Analyze the average waiting time (difference between booking time and trip start time) for different pickup locations. 
-- Ans.
Select pickup_location,
AVG(TIMESTAMPDIFF(MINUTE, booking_datetime, trip_start_time)) AS avg_wait_time
FROM booking
GROUP BY pickup_location;


 
-- (11.) Identify the most common reasons for trip cancellations from customer feedback. What actions can be taken to reduce cancellations? 
-- Ans. 
SELECT f.comments AS cancellation_reason,
COUNT(*) AS frequency
FROM booking b
LEFT JOIN feedback f
ON b.booking_id = f.booking_id
WHERE b.status = 'Cancelled'
AND f.comments IS NOT NULL
GROUP BY f.comments
ORDER BY frequency DESC;



-- (12.) Find out whether shorter trips (low-distance) contribute significantly to revenue. Should the company encourage more short-distance rides? 
-- Ans.
SELECT CASE WHEN trip_distance_km < 5 THEN 'Short Trip' ELSE 'Long Trip' END AS trip_type,
SUM(fare_amount) AS Total_Revenue
FROM trip_details
GROUP BY trip_type;
Select * from trip_details;


-- 															-- Comparative & Predictive Analysis --																			-- 				 

-- (13.) Compare the revenue generated from 'Sedan' and 'SUV' cabs. Should the company invest more in a particular vehicle type? 
-- Ans.
SELECT car_type, count(*)  Total_trip, sum(fare_amount) Cab_Total_Revenue from vehicles
where car_type in ("SUV" ,"Sedan") and status="Completed"
GROUP BY car_type
ORDER BY Cab_Total_Revenue DESC;
select count(*) from vehicles;

-- (14.) Predict which customers are likely to stop using the service based on their last booking date and frequency of rides. How can customer retention be improved? 
-- Ans.
SELECT customer_id, MAX(booking_datetime) AS last_booking
FROM booking
GROUP BY customer_id
HAVING last_booking < DATE_SUB(CURDATE(), INTERVAL 3 MONTH);


-- (15.) Analyze whether weekend bookings differ significantly from weekday bookings. Should the company introduce dynamic pricing based on demand?
-- Ans.
SELECT case
    WHEN DAYOFWEEK(booking_datetime) IN (1,7) THEN 'Weekend'
    ELSE 'Weekday'
END AS day_type,
  COUNT(*) AS total_bookings,
  SUM(fare_amount) AS revenue
FROM booking
WHERE status = 'Completed'
GROUP BY day_type;




SELECT * FROM booking; 
SELECT * FROM customers;
SELECT * FROM drivers;
SELECT * FROM trip_details;
SELECT * FROM vehicles;
select * from feedback;
